export const REQUEST_NEW_FRIEND = 'REQUEST_NEW_FRIEND';
export const ADD_FRIEND_TO_LIST = 'ADD_FRIEND_TO_LIST';
export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const UPDATE_FRIENDS = 'UPDATE_FRIENDS';